[package]
name = "single-threaded-web-server"
version = "0.1.0"
authors = ["fibo <casati_gianluca@yahoo.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
